name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create environment file from secrets
      run: |
        mkdir -p src/environments
        cat > src/environments/environment.ts << EOF
        export const firebaseConfig = {
          apiKey: "AIzaSyAMajQkymTiHB35Z5gmSzy8ezCv432D87A",
          authDomain: "join-project-a437a.firebaseapp.com",
          databaseURL: "https://join-project-a437a-default-rtdb.europe-west1.firebasedatabase.app",
          projectId: "join-project-a437a",
          storageBucket: "join-project-a437a.firebasestorage.app",
          messagingSenderId: "848614889298",
          appId: "1:848614889298:web:c448e996f46de06252cc8b",
          measurementId: "G-X4R986D1CT"
        };

        export const environment = {
          production: true,
          firebase: firebaseConfig
        };
        EOF
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
