name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create environment file from secrets
      run: |
        mkdir -p src/environments
        cat > src/environments/environment.ts << EOF
        export const firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}",
          measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
        };

        export const environment = {
          production: true,
          firebase: firebaseConfig
        };
        EOF
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
